### PR TITLE
Add Session.series_list to list series

### PR DESCRIPTION
**Pull request by Naouak**
(Sorry for the PR flood 😅)

### CODE REVIEW

**Comment by rkuykendall** [comment]
No, I love it! I'm glad you're finding it so easy to develop with!

We're also gonna look at getting https://github.com/rkuykendall/marvelous/pull/6 merged next week. So it's nice to have some updates to this 4-year old project. I still use it every few weeks though to manage my own reading.

Mind rebasing?

**Comment by Naouak** [comment]
It's rebased. I'm also building a tool to manage my reading. I've got a Marvel Unlimited subscription back in November and I can't find a nice tool to manage what I've read so far and reading lists so I'm building one.

**Comment by rkuykendall** [comment]
That's great! That's why I built https://github.com/weeklypulls and this library with @toyg, but it's admittedly been very stop-and-go. I'd love to hear about your project sometime!

**Comment by rkuykendall** [comment]
Released in [v1.1.1](https://pypi.org/project/marvelous/1.1.1/).

**Pull request merged**
